# Generated by Django 3.0.5 on 2022-12-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'toppings'},
        ),
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=models.TextField(),
        ),
    ]
