# Generated by Django 3.0.5 on 2022-12-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_auto_20221211_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
